name: 构建和发布 DNSCache

on:
  push:
    tags:
      - 'v*'  # 推送标签时触发，如 v1.0.0
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka ordered-set zstandard

      - name: 安装 MinGW（Nuitka 所需）
        run: |
          choco install mingw -y

      - name: 提取版本号
        id: get_version
        run: |
          $version = "${{ github.ref_name }}"
          if ($version -match 'v(\d+)\.(\d+)\.(\d+)') {
            $v1 = $Matches[1]
            $v2 = $Matches[2]
            $v3 = $Matches[3]
            echo "VERSION=$v1,$v2,$v3,0" | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            echo "VERSION=1,0,0,0" | Out-File -FilePath $env:GITHUB_ENV -Append
          }

      - name: 使用 Nuitka 构建
        run: |
          python -m nuitka --standalone --onefile --follow-imports --plugin-enable=numpy --windows-icon-from-ico=favicon.ico --windows-company-name="DNS Cache" --windows-product-name="DNS 缓存工具" --windows-file-version=${{ env.VERSION }} --windows-product-version=${{ env.VERSION }} --output-dir=dist dns_cache_tool.py

      - name: 创建版本信息
        run: |
          echo "版本: ${{ github.ref_name }}" > dist/version.txt
          echo "构建时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" >> dist/version.txt
          echo "提交: ${{ github.sha }}" >> dist/version.txt

      - name: 创建压缩包
        run: |
          cd dist
          Compress-Archive -Path dns_cache_tool.exe, version.txt -DestinationPath DNSCache_${{ github.ref_name }}.zip
          cd ..

      - name: 创建发布
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/DNSCache_${{ github.ref_name }}.zip
            dist/dns_cache_tool.exe
          draft: false
          prerelease: false
          name: DNSCache ${{ github.ref_name }}
          body: |
            DNS缓存工具 ${{ github.ref_name }} 发布
            
            ## 下载
            - [完整程序包 (zip)](DNSCache_${{ github.ref_name }}.zip)
            - [单文件可执行程序 (exe)](dns_cache_tool.exe)
            
            ## 更新内容
            - 自动构建版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
