name: Build-DNSCache
run-name: Build ${{ github.ref_name }} for DNSCache

on:
  push:
    tags:
      - 'v*'  # Push tags matching v*, i.e. v1.0.0
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka ordered-set zstandard

      - name: Install MinGW for Nuitka
        run: |
          choco install mingw -y

      - name: Generate version from date
        id: generate_version
        run: |
          $date = Get-Date
          $version = "$($date.Year).$($date.Month.ToString('00')).$($date.Day.ToString('00')).$($date.Hour.ToString('00'))"
          echo "DATE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Using version from date: $version"

      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone --onefile --follow-imports --enable-plugin=tk-inter,anti-bloat --lto=yes --windows-icon-from-ico=favicon.ico --windows-company-name="DNS Cache" --windows-product-name="DNS Cache Tool" --windows-file-version="${{ env.DATE_VERSION }}" --windows-product-version="${{ env.DATE_VERSION }}" --assume-yes-for-downloads --show-progress --output-dir=dist --output-filename=DNSCacheGUI gui.py

      - name: Create version info
        run: |
          echo "版本: ${{ github.ref_name }}" > dist/version.txt
          echo "构建时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" >> dist/version.txt
          echo "GUI 构建版本: ${{ env.DATE_VERSION }}" >> dist/version.txt
          echo "提交: ${{ github.sha }}" >> dist/version.txt

      - name: Create archive
        run: |
          cd dist
          Compress-Archive -Path DNSCacheGUI.exe, version.txt -DestinationPath DNSCacheGUI_${{ github.ref_name }}.zip
          cd ..

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/DNSCacheGUI_${{ github.ref_name }}.zip
            dist/DNSCacheGUI.exe
          draft: false
          prerelease: false
          name: DNS Cache Tool GUI ${{ github.ref_name }}
          body: |
            DNS Cache Tool GUI ${{ github.ref_name }} Release
            
            ## Downloads
            - [Windows Application Bundle (zip)](DNSCacheGUI_${{ github.ref_name }}.zip)
            - [Windows Executable (exe)](DNSCacheGUI.exe)
            
            ## Release Notes
            - GUI Application (Build Version: ${{ env.DATE_VERSION }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
